# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
ENABLE_LINTERS:
  - ACTION_ACTIONLINT
  - GO_GOLANGCI_LINT
  - JAVASCRIPT_PRETTIER
  - JSX_ESLINT
  - MAKEFILE_CHECKMAKE
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - SPELL_CSPELL
  - RUBY_RUBOCOP
  - YAML_PRETTIER
  - YAML_YAMLLINT
# DISABLE:
# - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
# - SPELL # Uncomment to disable checks of spelling mistakes
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
